[package]
name = "as7331-rs"
version = "0.1.2"
authors = ["tuemb <nvtu96@gmail.com>"]
edition = "2021"
description   = "as7331 driver in Rust for embedded devices"
license       = "MIT OR Apache-2.0"
repository    = "https://github.com/TuEmb/as7331-rs"

[dependencies]
log = "0.4.22"
